Entrega 4 Marcos Garcia Postigo
FacultadInformatica-LinkedData/Curso2022-2023 pull request #101
Opened 2022-09-30 13:51 UTC by bayoneta101

2022-09-30 20:16 UTC, dgarijo requested changes

2022-09-30 20:16 UTC, dgarijo commented on Assignment4/bayoneta101-190375/task06.py
> +!pip install rdflib
won't work in python. This is  Notebook magic

2022-09-30 20:16 UTC, dgarijo commented on Assignment4/bayoneta101-190375/task07.py
> +     ?x rdfs:subClassOf ns:Person }
use * or + to list all subclasses of Person, recursively

2022-09-30 20:16 UTC, dgarijo commented on Assignment4/bayoneta101-190375/task07.py
> +      ?t rdfs:subClassOf ns:Person
same as above

2022-10-01 17:30 UTC, bayoneta101 commented
Añadido group assigment 1, ahora arreglare el task 6 y 7

2022-10-02 13:07 UTC, bayoneta101 commented
Branch listo para merge, con task 6,7 y group assigment 1

2022-10-02 17:38 UTC, dgarijo commented on Assignment4/bayoneta101-190375/task07.py
> +    ?x rdf:type ns:Person.
This is listing all persons, not subclasses of person

2022-10-02 17:38 UTC, dgarijo requested changes
Please fix the pending error.

2022-10-03 13:38 UTC, dgarijo approved these changes

2022-10-03 13:38 UTC, merged