Graph Davidppp0.png
FacultadInformatica-LinkedData/Curso2022-2023 pull request #40
Opened 2022-09-14 19:48 UTC by Davidppp0

Draft of the graph.
If you see an error, please let me know.

2022-09-15 17:16 UTC, Davidppp0 commented
Add ttl

2022-09-19 17:09 UTC, ocorcho requested changes

2022-09-19 17:09 UTC, ocorcho commented on Assignment2/Davidppp0.ttl
> +                   tortuga:atTime "2022-09-12T12:01:12"^^xsd:date .
xsd:dateTime

2022-09-19 17:09 UTC, ocorcho commented on Assignment2/Davidppp0-fromJSONtoJSON-LD.jsonld
> +        "age": "rdfs:label",
Modify "rdfs:label" into schema:age or alike

2022-09-25 20:06 UTC, ocorcho commented
I still see the issue with the JSON-LD, but accepted.

2022-09-25 20:06 UTC, merged