Assignment 2
FacultadInformatica-LinkedData/Curso2022-2023 pull request #50
Opened 2022-09-16 09:31 UTC by alexfcab

2022-09-25 20:12 UTC, ocorcho requested changes

2022-09-25 20:12 UTC, ocorcho commented on Assignment2/alexfcab-fromJSONtoJSON-LD.jsonld
> +        "hometown": "rdfs:label",
These cannot be rdfs:label. The same with other properties

2022-09-29 16:38 UTC, ocorcho commented
JSON-LD is not fixed. The rest ok
Now to @dgarijo for assignment 4.

2022-09-29 16:53 UTC, alexfcab commented
Is JSON-LD fixed now?

2022-09-29 19:42 UTC, dgarijo requested changes
Small changes requested

2022-09-29 19:42 UTC, dgarijo commented on Assignment4/alexfcab-200385/task06.py
> +!pip install rdflib
This won't work in Python. It's notebook magic

2022-09-29 19:42 UTC, dgarijo commented on Assignment4/alexfcab-200385/task06.py
> +g.add((ns.JohnSmith, vcard.work, ns.UPM))
This property does not exist in vcard

2022-09-29 19:42 UTC, dgarijo commented on Assignment4/alexfcab-200385/task07.py
> +    print(s2, "is subclass of", s, "and subclass of", o)
second loop is not needed

2022-09-29 19:42 UTC, dgarijo commented on Assignment4/alexfcab-200385/task07.py
> +	  ?x (rdfs:subClassOf/rdfs:subClassOf*) ns:Person
only 1 subclassOf is ok

2022-09-29 20:09 UTC, alexfcab commented
@dgarijo could you please review it again, I made some changes according to your annotations

2022-09-29 20:23 UTC, dgarijo commented on Assignment4/alexfcab-200385/task06.py
> +g.add((ns.JohnSmith, vcard.worksAt, ns.UPM))
worksAt does not exist neither in vcard. Create your own under the ns  namespace

2022-09-29 20:24 UTC, dgarijo requested changes
mini changes needed

2022-09-30 10:32 UTC, alexfcab commented
@dgarijo is task06 okay now? same with jsontojsonld @ocorcho

2022-09-30 17:50 UTC, dgarijo approved these changes

2022-09-30 17:50 UTC, dgarijo commented
@ocorcho assignment 4 is now ok. Please merge when appropriate

2022-09-30 21:29 UTC, merged