Assigment 2b
FacultadInformatica-LinkedData/Curso2022-2023 pull request #57
Opened 2022-09-17 17:37 UTC by poll2000

2022-09-25 20:14 UTC, ocorcho requested changes

2022-09-25 20:14 UTC, ocorcho commented on Assignment2/poll2000-fromJSONtoJSON-LD.jsonld
> +        "hometown": "rdfs:label",
These cannot be rdfs:label. The same with other properties

2022-09-29 16:40 UTC, ocorcho commented
Assignment 2b has not been completed.
Now @dgarijo to check the assignment 4

2022-09-29 19:22 UTC, dgarijo requested changes
Small changes from tasks 6 and 7

2022-09-29 19:22 UTC, dgarijo commented on Assignment4/poll2000-200386/task06.py
> +!pip install rdflib
This won't work in python. It's notebook magic

2022-09-29 19:22 UTC, dgarijo commented on Assignment4/poll2000-200386/task06.py
> +g.add((ns.JohnSmith, vcard.work, ns.UPM))
not a property in vcard.

2022-09-29 19:22 UTC, dgarijo commented on Assignment4/poll2000-200386/task07.py
> +    print(sub2, "is subclass of ", sub, "which in turn is of Person type.")
second loop not needed

2022-09-29 19:22 UTC, dgarijo commented on Assignment4/poll2000-200386/task07.py
> +	  ?x (rdfs:subClassOf/rdfs:subClassOf*) ns:Person
not needed here. with subclassOf is enough

2022-09-30 17:46 UTC, dgarijo approved these changes

2022-09-30 17:47 UTC, dgarijo commented
@ocorcho assignment 4 is ok. Shall I merge even though there are changes requested by you?

2022-09-30 21:30 UTC, merged