Assignment4 - task6 and task7
FacultadInformatica-LinkedData/Curso2022-2023 pull request #63
Opened 2022-09-26 19:02 UTC by Alfonsogm

2022-09-29 18:39 UTC, dgarijo commented on Assignment4/Alfonsogm-160068/task06.py
> +!pip install rdflib
won't work in python (this is for the notebooks only). Try and run this script

2022-09-29 18:42 UTC, dgarijo requested changes
Please fix the issues

2022-09-29 18:42 UTC, dgarijo commented on Assignment4/Alfonsogm-160068/task07.py
> +
You are missing listing all inividuals of the subclasses of Person

2022-09-29 18:42 UTC, dgarijo commented on Assignment4/Alfonsogm-160068/task07.py
> +  ?subj ?p1 ns:Person
this is listing all the properties linked to Person, not all instances.
Also, you are missing subclasses. Incorrect

2022-09-29 18:42 UTC, dgarijo commented on Assignment4/Alfonsogm-160068/task07.py
> +    print(s1,p1,o1)
missing subclasses of person. Almost correct

2022-09-30 09:01 UTC, Alfonsogm commented
Issues ready to be reviewed.

2022-09-30 17:39 UTC, merged