Submitting assignment 4
FacultadInformatica-LinkedData/Curso2022-2023 pull request #69
Opened 2022-09-28 16:47 UTC by Rulo401

2022-09-29 20:05 UTC, dgarijo requested changes
Small changes requested

2022-09-29 20:05 UTC, dgarijo commented on Assignment4/Rulo401-190243/task06.py
> +!pip install rdflib
won't work in python. This is notebook magic

2022-09-29 20:05 UTC, dgarijo commented on Assignment4/Rulo401-190243/task07.py
> +    ?Class  RDFS:subClassOf ns:Person}
you need to have ALL the subclasses. Hint you may use chained properties with "*" for 0..n repetitions

2022-09-29 20:05 UTC, dgarijo commented on Assignment4/Rulo401-190243/task07.py
> +  }GROUP BY ?Person
nicely done, but it has the same issue as above. We need all the subclass hierarchy, not 1 level

2022-09-29 20:05 UTC, dgarijo commented on Assignment4/Rulo401-190243/task09.py
> +      g3.add((r2.Person, OWL.sameAs, r1[0]))
sameAs is reflexive, so you only need to assert it in 1 direction

2022-09-30 16:25 UTC, Rulo401 commented
@dgarijo Requested changes are done

2022-09-30 21:03 UTC, dgarijo approved these changes

2022-09-30 21:03 UTC, merged