Update
FacultadInformatica-LinkedData/Curso2022-2023 pull request #70
Opened 2022-09-28 18:37 UTC by 0MLG

2022-09-28 19:29 UTC, dgarijo commented
@0MLG for Assignemnt 4, you have to create a new folder following the instructions in the slides.
As it is, this is not a valid PR

2022-09-29 10:23 UTC, 0MLG commented
Sorry, I fixed it. Thank you for the warning

2022-09-29 16:41 UTC, ocorcho commented
Assignment 2 is not correct, but do not correct any more. 
Now @dgarijo can continue with hassignment 4.

2022-09-29 20:01 UTC, dgarijo requested changes
Small change request in exercise 6. Exercise 7 is perfect

2022-09-29 20:01 UTC, dgarijo commented on Assignment4/0MLG-190260/task06.py
> +!pip install rdflib
Won't work in python. This is notebook magic

2022-09-29 20:01 UTC, dgarijo commented on Assignment4/0MLG-190260/task06.py
> +g.add((ns.UPM, VCARD.AGENT, ns.JohnSmith))
This is wrong. VCARD.Agent is not a property. If you cannot find an appropriate property, create your own in the ns namespace

2022-09-30 13:23 UTC, 0MLG commented on Assignment4/0MLG-190260/task06.py
> +g.add((ns.UPM, VCARD.AGENT, ns.JohnSmith))
@dgarijo thanks for the feedback! I just fixed it

2022-09-30 18:15 UTC, merged