Task06, 07 and 08 are done
FacultadInformatica-LinkedData/Curso2022-2023 pull request #71
Opened 2022-09-28 19:22 UTC by miguex255

2022-09-29 20:54 UTC, dgarijo requested changes

2022-09-29 20:54 UTC, dgarijo commented on Assignment4/miguex255-190322/Task06.py
> +g.add((ns.JohnSmith, VCARD.Work, ns.UPM))
vcard work does not exist in vcard. Create your own in your namespace

2022-09-29 20:54 UTC, dgarijo commented on Assignment4/miguex255-190322/Task07.py
> +    ?s (rdfs:subClassOf/rdfs:subClassOf*) ns:Person.
here 1 subclass of is enough

2022-09-29 20:54 UTC, dgarijo commented on Assignment4/miguex255-190322/Task08.py
> +#Extraemos name, family name y email del segundo grafo y lo añadimos al primero
They have to be from the class Person.

2022-09-30 21:01 UTC, miguex255 commented
Good evening teacher, sorry about the commit including the notebooks checkpoint folder, I forgot to delete it. It won't happen again.

2022-09-30 21:28 UTC, dgarijo commented
@miguex255 you still have the checkpoints. And you have modified the class material notebooks. I cannot accept it as it is, sorry

2022-09-30 21:41 UTC, miguex255 commented
Teacher, to try to fix it, do I have to create another pull-request and close this one.?

2022-09-30 22:05 UTC, dgarijo commented
no, just commit new changes as you have done.

2022-09-30 22:06 UTC, dgarijo commented
You are still submitting changes to the class notebooks. I cannot accept the PR :(

2022-10-02 14:35 UTC, dgarijo commented
You are still adding notebook checkpoints and changes to notebooks. This PR is not acceptable

2022-10-02 14:48 UTC, closed without merging