Assignment 4
FacultadInformatica-LinkedData/Curso2022-2023 pull request #78
Opened 2022-09-29 15:21 UTC by RakshaCode

2022-09-29 20:37 UTC, dgarijo requested changes
minimal changes requested

2022-09-29 20:37 UTC, dgarijo commented on Assignment4/RakshaCode-190165/task06.py
> +g.add((ns.JohnSmith, vcard.Works, ns.UPM))
vcard.Works does not exist. Create it your own ns

2022-09-29 20:37 UTC, dgarijo commented on Assignment4/RakshaCode-190165/task07.py
> +  ?subClass rdfs:subClassOf ns:Person .
use * to chain subClassOf properties

2022-09-29 20:37 UTC, dgarijo commented on Assignment4/RakshaCode-190165/task07.py
> +}
same as above

2022-09-30 13:30 UTC, RakshaCode commented
@dgarijo Thanks for the review

2022-09-30 18:16 UTC, merged